### ISSUE TITLE
Autocomplete not showing results.

### ISSUE THREAD

**Issue by razeta** [yceruto/rich-form-bundle#3]
Hello.

So I have an collection type in easyadmin in Symfony 5.

`- { property: 'productos', type: 'collection', label: "Test", type_options: { entry_type: 'App\Form\ProductoType', by_reference: false} }        `    

And Im trying to use the Entity2Type in my form ProductoType.
```
 ->add('especie',  Entity2Type::class, [
				// looks for choices from this entity
				'class' => Especie::class,			
				'search_by' => 'nombre',
				// used to render a select box, check boxes or radios
				// 'multiple' => true,
				// 'expanded' => true,
				'required'=>false,
				'label' => "Especie:",
				'attr'   =>  array(
					'class'   => '')
			])
```
I havent been able to make it work, the field comes empty.  If I change the Entity2Type to EntityType I get the 2 registers, but no autocomplete.

I have no JS errors, all files are shown in the html header.

Easyadmin yaml
```
        assets:
            css:
                - 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css'
            js:
                - 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.full.min.js'
                - 'bundles/richform/entity2.js'
                - 'build/js/app_chosen.js'
         
```
In need to have one field of the embedded form with autocomplete.

Any ideas.

Thanks.
